name: my_climbing_trek
description: My Climbing Trek

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.11+13


environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8 
  intl: ^0.19.0
  uuid: ^4.4.0
  collection: ^1.18.0
  dartz: ^0.10.1
  get_it: 7.7.0 
  # Интерфейсные фичи
  flutter_hooks: ^0.20.5
  flutter_colorpicker: ^1.0.3
  url_launcher: ^6.2.6
  flutter_slidable: ^3.1.0
  cached_network_image: ^3.3.1
  # Управление состояниями
  injectable: ^2.4.1 
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  # Для функции поделиться данными тренировки
  screenshot: ^2.3.0
  share_plus: ^8.0.3
  # Локальное хранение данных в NoSQL базе
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Локальное хранение данных в SQL базе
  drift: ^2.17.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.3
  path: ^1.9.0
  #Интеграция со службами Firebase 
  firebase_core: ^2.30.0
  firebase_analytics: ^10.10.2
  firebase_crashlytics: ^3.5.2
  firebase_app_check: ^0.2.2+2
  #Удаленная база данных
  cloud_firestore: ^4.17.0
  #Проверка интернет соединения
  internet_connection_checker: ^1.0.0+1
  #Аунтификация
  firebase_auth: ^4.19.2

  #Выбор изображения с устройства
  image_picker: ^1.1.0
  #Диалоги выбора и сохранения файла
  file_saver: ^0.2.12
  file_selector: ^1.0.3
  # Кеширование изображений
  flutter_cache_manager: ^3.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  drift_dev: ^2.17.0

  flutter_lints: ^3.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

 
