name: my_climbing_trek
description: My Climbing Trek

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.10+12


environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5 
  intl: ^0.18.1
  uuid: ^3.0.7
  collection: ^1.17.1
  dartz: ^0.10.1
  get_it: 7.6.0
  # Интерфейсные фичи
  flutter_hooks: ^0.18.6
  flutter_colorpicker: ^1.0.3
  url_launcher: ^6.1.11
  flutter_slidable: ^3.0.0
  cached_network_image: ^3.2.3
  # Управление состояниями
  injectable: ^2.1.2 
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  # Для функции поделиться данными тренировки
  screenshot: ^2.1.0
  share_plus: ^7.0.2
  # Локальное хранение данных в NoSQL базе
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Локальное хранение данных в SQL базе
  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.0.15
  path: ^1.8.3
  #Интеграция со службами Firebase 
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.3.3
  #Удаленная база данных
  cloud_firestore: ^4.8.1
  #Проверка интернет соединения
  internet_connection_checker: ^1.0.0+1
  #Аунтификация
  firebase_auth: ^4.6.3

  #Выбор изображения с устройства
  image_picker: ^0.8.9
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  injectable_generator: ^2.1.6
  drift_dev: ^2.8.3

  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

 
